name: GitLab'a Yedekle

on:
  push:
    branches:
      - '*'
  delete:
    branches:
      - '*'

# GitHub'ın istediği Node 24 zorlamasını çevre değişkeni olarak ekliyoruz
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLab'a Aynala
        run: |
          # Git kimlik bilgilerini geçici olarak ayarla (Olası push hatalarını engellemek için)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # GitLab uzak sunucusunu tanımla
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/PisiLinux/main.git
          
          # Aynalama işlemini gerçekleştir
          git push gitlab --prune --all
          git push gitlab --prune --tags
